# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='empty@empty.kg', max_length=254),
            preserve_default=False,
        ),
    ]
